from .about import AboutView
from .confirmation import ConfirmView
from .delete_post import DeletePostView
from .editprofile import EditProfileView
from .home import HomeView
from .login import LoginView
from .logout import LogoutView
from .new_post import NewPostView
from .post import PostView
from .registration import RegistrationView
from .userprofile import UserProfileView
