# Generated by Django 4.1.7 on 2023-03-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='preview_image_path',
        ),
    ]
