# Generated by Django 4.1.7 on 2023-03-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0005_remove_images_preview_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='preview_image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
