# Generated by Django 4.1.7 on 2023-03-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0006_images_preview_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image_path',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='images',
            name='preview_image_url',
        ),
        migrations.AddField(
            model_name='images',
            name='preview_image',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
    ]
