# Generated by Django 4.1.7 on 2023-03-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0007_rename_image_path_images_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='images/preview/'),
        ),
    ]
