# Generated by Django 4.1.7 on 2023-03-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0008_alter_images_image_alter_images_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
