# Generated by Django 4.1.7 on 2023-03-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catapp", "0010_remove_images_preview_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="preview_image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
